version: "3.3"

services:
  world-cars-api:
    container_name: world-cars-api
    restart: always
    image: node:20.10
    ports:
      - "4001:3007"
    volumes:
      - ./:/usr/src/world-cars
    working_dir: /usr/src/world-cars
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build && npm run start:prod"

  world-cars-batch:
    container_name: world-cars-batch
    restart: unless-stopped
    image: node:20.10
    ports:
      - "4002:3008"
    volumes:
      - ./:/usr/src/world-cars
    working_dir: /usr/src/world-cars
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
